# Generated by Django 3.1.6 on 2021-03-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210316_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora y fecha de creacion'),
        ),
        migrations.CreateModel(
            name='UsersFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_followed', models.ManyToManyField(related_name='users_followed', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Seguidos')),
            ],
        ),
    ]
